config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', to: "search#search"

  concern :rateable do
    member do
      patch :rate_up
      patch :rate_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  resources :questions, concerns: %i[rateable commentable] do
    resources :answers, shallow: true, concerns: %i[rateable commentable], only: %i[create update destroy] do
      member do
        patch :choose_as_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: 'questions#index'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy

  after_save :create_subscription

  include Rateable
  include Commentable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  def best_answer
    answers.best_answer.first
  end

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  def subscription(user)
    subscriptions.find_by(user: user)
  end

  private

  def create_subscription
    subscriptions.create(user_id: user_id, question_id: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :question, only: %i[show update destroy]
  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      head :ok
    else
      head 422
    end
  end

  def update
    if question.update(question_params)
      head :ok
    else
      head 422
    end
  end

  def destroy
    if question.destroy
      head :ok
    else
      head 422
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[name url],
                                     files: [])
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_question_owner_id, only: :show

  after_action :publish_question, only: :create

  include Rated
  include Commented

  authorize_resource

  def index; end

  def show
    answer.links.build
    gon.question_id = question.id
  end

  def new
    @question = Question.new
    question.links.build
    question.build_reward
  end

  def create
    question.user = current_user
    if question.save
      redirect_to question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    question.destroy
    flash[:notice] = 'Your question deleted successfully'
    redirect_to root_path
  end

  private

  def publish_question
    return if question.errors.any?

    QuestionsChannel.broadcast_to('questions', question)
  end

  def set_question_owner_id
    gon.question_owner_id = question.user.id
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new(question_params)
  end

  helper_method :question

  def questions
    @questions ||= Question.all
  end

  helper_method :questions

  def answers
    @answers ||= question.answers.sort_by_best
  end

  helper_method :answers

  def answer
    @answer ||= question.answers.build
  end

  helper_method :answer

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [],
                                     reward_attributes: [:title, :image],
                                     links_attributes: [:name, :url, :done, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.question_errors
  = render 'shared/errors', resource: question

= form_with model: question, class: "form-group #{'hidden' if hidden}", html: { id: "question-id-#{question.id}" } do |f|
  = f.label :title, class: 'mt-2'
  = f.text_field :title, class: 'form-control'
  = f.label :body, class: 'mt-2'
  = f.text_area :body, class: 'form-control'
  = f.label :files, class: 'mt-2'
  = f.file_field :files, multiple: true, class: 'form-control'
  #new-links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
  #best-answer-reward
    = f.fields_for :reward do |reward|
      p
        = reward.label 'Reward title:'
        = reward.text_field :title
      p
        = reward.label :image
        = reward.file_field :image

  = f.submit 'Save', class: 'btn btn-primary mt-2'

app/views/questions/_question.html.slim
div id="question-#{question.id}"
  - cache_unless current_user.try(:admin), ['question_title', question] do
    div
      span style="font-size: 200%;"
        = question.title
      span.float-right.mt-2
        = render 'subscriptions/subscription'

  - if %i[edit destroy].any? { |action| can? action, question }
    = link_to 'Delete', question_path(question), class: 'float-right', method: :delete
    = link_to 'Edit', '#', class: 'edit-question-link float-right mr-4', data: { question_id: question.id }
    = render 'form', hidden: true
    hr
  - cache_unless current_user.try(:admin), ['question_body_with_attachments', question] do
    p
      = question.body

    .attached-files
    - if question.files.attached?
      = render question.files

    .attached-links
      = render question.links

    hr

  .question-rates
    - if %i[rate_up rate_down cancel_vote].any? { |action| can? action, question }
      = render 'shared/rates', resource: question

  hr

  .comment-errors
  h4
    = "Comments:"
  .comments
    = render question.comments

  .new-comment
    = render 'shared/new_comment', resource: question

app/views/questions/create_comment.js.erb
$('.comment-errors').html('<%= render 'shared/errors', resource: comment %>');

app/views/questions/index.html.slim
div class="questions"
  h1 class='mt-2' = 'All Questions'

  - questions.each do |question|
    .card.border-dark.mt-3
      .card-header
        = link_to question.title, question
        span.float-right
          = "by #{question.user.email}"
      .card-body
        = question.body

app/views/questions/new.html.slim
h3 class='mt-2' = "Ask your question"

= render 'form', hidden: false

= link_to 'Back', questions_path, class: 'btn btn-outline-primary'

app/views/questions/show.html.slim
div class="question"
  = render question

h3 = "#{question.answers.count} Answers"

.answers
  div id="question-#{question.id}-answers"
    = render answers

- if can?(:create, Answer)
  .answer_errors
  = form_with model: [question, answer], class: 'new-answer' do |f|
    = f.label :body, 'Your answer', class: 'mt-2'
    = f.text_area :body, rows: 4, class: 'form-control mt-1'
    = f.label :files, class: 'mt-2'
    = f.file_field :files, multiple: true, class: 'form-control mt-1'
    #new-links
      .links
        = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    = f.submit 'Post Your Answer', class: 'btn btn-primary mt-2'

p= link_to 'Back', questions_path, class: 'btn btn-outline-primary mt-2'

app/views/questions/update.js.erb
<% if question.errors.present? %>
  $('.question_errors').html('<%= render 'shared/errors', resource: question %>')
<% else %>
  var form = document.querySelector('.form-group')
  form.classList.add('hidden')
  $('#question-<%= question.id %>').html('<%= j render question %>')
<% end %>