config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', to: "search#search"

  concern :rateable do
    member do
      patch :rate_up
      patch :rate_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  resources :questions, concerns: %i[rateable commentable] do
    resources :answers, shallow: true, concerns: %i[rateable commentable], only: %i[create update destroy] do
      member do
        patch :choose_as_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: 'questions#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities
    can :read, :all
    cannot :read, Reward
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    can [:rate_up, :rate_down, :cancel_vote], [Question, Answer] do |rate|
      !user.is_author?(rate)
    end
    can :read, :all
    can :choose_as_best, Answer, question: { user_id: @user.id }
    can :create, [Question, Answer, Link, Subscription]
    can :update, [Question, Answer], user_id: @user.id
    can :destroy, [Question, Answer, Subscription], user_id: @user.id
    can :destroy, ActiveStorage::Attachment, record: { user_id: @user.id }
    can :destroy, Link, linkable: { user_id: @user.id }
    can :create_comment, [Question, Answer]
    can :me, User, { user_id: user.id }
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable
  after_create :send_notice

  include Rateable
  include Commentable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  has_many_attached :files

  scope :best_answer, -> { where(best: true) }
  scope :sort_by_best, -> { order(best: :desc) }

  def select_best
    transaction do
      question.best_answer&.update!(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def send_notice
    NewAnswerNoticeJob.perform_later(self) if question.subscriptions.any?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates_presence_of :body
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates_format_of :url, with: URI::regexp

  def is_gist?
    URI.parse(url).host.include?('gist')
  end

  def get_gist
    client = Octokit::Client.new
    gist_id = URI.parse(url).path.split('/').last
    client.gist(gist_id)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy

  after_save :create_subscription

  include Rateable
  include Commentable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  def best_answer
    answers.best_answer.first
  end

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end

  def subscription(user)
    subscriptions.find_by(user: user)
  end

  private

  def create_subscription
    subscriptions.create(user_id: user_id, question_id: self)
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :rateable, polymorphic: true

  validates :status, presence: true
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :title, :image, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github vkontakte]

  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :rewards
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def is_author?(object)
    id == object.user_id
  end

  def self.find_for_oauth(auth)
    FindForOauthService.new(auth).call
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def destroy
    link.destroy
  end

  private

  def link
    @link ||= Link.find(params[:id])
  end

  helper_method :link
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THQna</title>
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
  <%= render 'shared/nav' %>
  <%= render 'shared/second_nav' %>
    <div class="row justify-content-center mt-3">
      <div class="col col-md-8">
        <div id="flash">
          <%= render partial: 'shared/flash' %>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :p, message, class: 'alert alert-info mt-4'

app/views/shared/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    p
      = f.text_field :name
  .field
    = f.label :url, 'Link url'
    p
      = f.text_field :url
  = link_to_remove_association 'Delete link', f

app/views/shared/_nav.html.slim
nav class='navbar navbar-light bg-dark'
  div class='container'
    - if user_signed_in?
      span.navbar-brand style='color: white;'
        = "Welcome, #{current_user.email} "
      ul.navbar-nav
        li.nav-item
          = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link', style: 'color: white;'
        li.nav-item
          = link_to 'Rewards', rewards_path, class: 'nav-link', style: 'color: white;'
    - else
      span.navbar-brand style='color: white;'
        = "Welcome, Guest!"
      ul.navbar-nav
        li.nav-item
          = link_to 'Log in', new_user_session_path, class: 'nav-link', style: 'color: white;'
        li.nav-item
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link', style: 'color: white;'

app/views/shared/_new_comment.html.slim
- if user_signed_in?
  = form_with model: [resource, resource.comments.build], url: polymorphic_path([:create_comment, resource]), class: 'form-group' do |f|
    = f.label :body, "Post New Comment:"
    = f.text_area :body, class: 'form-control comment-text'
    = f.submit 'Post Comment', class: 'btn btn-outline-primary mt-2'

app/views/shared/_rates.html.slim
p class = "#{resource.class.name.downcase}-rating"
  = "#{resource.class.name}'s rating: #{resource.rating}"

.rate-actions
  = link_to '+',
          [:rate_up, resource],
          class: 'mr-2',
          method: :patch,
          data: { type: :json },
          remote: true
  = link_to '-',
          [:rate_down, resource],
          class: 'mr-2',
          method: :patch,
          data: { type: :json },
          remote: true
  = link_to 'cancel vote',
          [:cancel_vote, resource],
          method: :delete,
          data: { type: :json },
          remote: true

app/views/shared/_second_nav.html.slim
nav class='navbar navbar-light bg-light shadow'
  .container style="height: 40px;"
    - if can?(:create, Question)
      p.navbar-nav
        = link_to 'Ask question', new_question_path, class: 'new-question-link nav-item'

    = form_with url: search_path, scope: :search, method: :get, class: 'form-inline', local: true do |f|
      = f.select :section, collection: SphinxSearchService::SECTIONS
      = f.text_field :q
      = f.submit 'Search', class: 'btn btn-outline-secondary ml-2'