config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', to: "search#search"

  concern :rateable do
    member do
      patch :rate_up
      patch :rate_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  resources :questions, concerns: %i[rateable commentable] do
    resources :answers, shallow: true, concerns: %i[rateable commentable], only: %i[create update destroy] do
      member do
        patch :choose_as_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable
  after_create :send_notice

  include Rateable
  include Commentable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  has_many_attached :files

  scope :best_answer, -> { where(best: true) }
  scope :sort_by_best, -> { order(best: :desc) }

  def select_best
    transaction do
      question.best_answer&.update!(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def send_notice
    NewAnswerNoticeJob.perform_later(self) if question.subscriptions.any?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  after_action :publish_answer, only: :create

  include Rated
  include Commented

  authorize_resource

  def create
    answer.user = current_user
    if answer.save
      respond_to do |format|
        format.js { flash.now[:notice] = 'Your answer posted successfully!' }
      end
    end
  end

  def update
    answer.update(answer_params)
  end

  def destroy
    answer.destroy
    format.js { flash.now[:notice] = 'Your answer deleted successfully!' }
  end

  def choose_as_best
    authorize! :choose_as_best, answer
    answer.select_best
  end

  private

  def publish_answer
    return if answer.errors.any?

    AnswersChannel.broadcast_to(
        "answers_#{question.id}",
        answer: answer,
        links: answer.links
    )
  end


  def answer
    @answer ||= Answer.with_attached_files.find_by(id: params[:id]) || question.answers.new(answer_params)
  end

  helper_method :answer

  def question
    @question ||= Question.with_attached_files.find_by(id: params[:question_id]) || answer.question
  end

  helper_method :question

  def answers
    @answers ||= question.answers
  end

  helper_method :answers

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :done, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :answer, only: %i[show update destroy]
  before_action :answers, only: %i[index create]

  authorize_resource

  def index
    render json: answers, each_serializer: AnswersSerializer
  end

  def show
    render json: answer
  end

  def create
    authorize! :create, question

    @answer = question.answers.new(answer_params)
    @answer.user = current_resource_owner
    if @answer.save
      head :ok
    else
      head 422
    end
  end

  def update
    if answer.update(answer_params)
      head :ok
    else
      head 422
    end
  end

  def destroy
    if answer.destroy
      head :ok
    else
      head 422
    end
  end

  private

  def answers
    @answers ||= question.reload.answers
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : answers.build(answer_params)
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   links_attributes: %i[name url],
                                   files: [])
  end

  def question
    @question = Question.with_attached_files.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id="answer-id-#{answer.id}" class="mt-3"
  div.card.border-secondary.mt-4
    .card-header
      - if answer.best
        span class="text-success mb-1 best-answer"
          p
            = 'This answer is best'
          - if question.reward
            img src="#{url_for(question.reward&.image)}"
      - cache_unless current_user.try(:admin), ['answer_body', answer] do
        span
          = answer.body
        span.float-right
          = answer.user.email

      div.actions.mt-4
        - if %i[edit destroy].any? { |action| can? action, answer }
          = link_to 'Delete', answer_path(answer), class: 'mr-4', method: :delete, remote: true
          = link_to 'Edit', '#', class: 'edit-answer-link mr-4', data: {answer_id: answer.id}
        - if can? :choose_as_best, answer
          = link_to 'Best', choose_as_best_answer_path(answer), method: :patch, remote: true
      - cache_unless current_user.try(:admin), ['answer_attachments', answer] do
        .attachments
          = render answer.files

        .attached-links
          = render answer.links

        hr

      = form_with model: answer, class: 'hidden form-group', html: {id: "edit-answer-#{answer.id}"} do |f|
        = f.label :body, 'Your answer'
        = f.text_area :body, class: 'form-control'
        = f.label :files
        = f.file_field :files, multiple: true, class: 'form-control'
        #new-links
          .links
            = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
        = f.submit 'Save', class: 'btn btn-outline-secondary'

      .answer-rates.mt-2
        - if %i[rate_up rate_down cancel_vote].any? { |action| can? action, answer }
          = render 'shared/rates', resource: answer

    .card-body
      .comment-errors
      h4
        = "Comments:"
      .comments
        = render answer.comments

      .new-comment
        = render 'shared/new_comment', resource: answer

app/views/answers/choose_as_best.js.erb
$('.answers').html('<%= j render answer.question.answers.sort_by_best %>')

app/views/answers/create.js.erb
$('.answer_errors').html('<%= render 'shared/errors', resource: answer %>')
$('#flash').html('<%= j render partial: 'shared/flash' %>')

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>')
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/create_comment.js.erb
$('.comment-errors').html('<%= render 'shared/errors', resource: comment %>');

app/views/answers/destroy.js.erb
$('#flash').html('<%= j render partial: 'shared/flash' %>')
$('<%= "#answer-id-#{answer.id}" %>').remove()

app/views/answers/update.js.erb
<% if answer.errors.present? %>
  $('.answer_errors').html('<%= render 'shared/errors', resource: answer %>')
<% else %>
  $('.answers <%= "#answer-id-#{answer.id}" %>').html('<%= j render answer %>')
<% end %>