config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount ActionCable.server => "/cable"

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', to: "search#search"

  concern :rateable do
    member do
      patch :rate_up
      patch :rate_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    post :create_comment, on: :member
  end

  resources :questions, concerns: %i[rateable commentable] do
    resources :answers, shallow: true, concerns: %i[rateable commentable], only: %i[create update destroy] do
      member do
        patch :choose_as_best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :links, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  root to: 'questions#index'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :question, only: :create
  before_action :subscription, only: :destroy

  authorize_resource

  def create
    question.subscriptions.create(user_id: current_user&.id)
  end

  def destroy
    @question = subscription.question
    subscription.destroy
  end

  private

  def question
    @question = Question.find(params[:question_id])
  end
  helper_method :question

  def subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.slim
.subscription
  -if current_user
    -if question.subscribed?(current_user)
      = button_to 'UNSUBSCRIBE', subscription_path(question.subscription(current_user)), remote: true, method: :delete, data: { type: :js }, class: 'btn btn-outline-primary'
    -else
      = button_to 'SUBSCRIBE', question_subscriptions_path(question), remote: true, data: { type: :js }, class: 'btn btn-outline-primary'

app/views/subscriptions/create.js.erb
$('.subscription').html('<%= j render 'subscription', question: question %>');

app/views/subscriptions/destroy.js.erb
$('.subscription').html('<%= j render 'subscription', question: @question %>');